---
name: Lint
on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lints and Scans
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo ⤵️
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@2332a7b74a6de0dda2e2221d575162eba76ba5e5 # v3.3.0
        with:
          dockerfile: docker/Dockerfile
          ignore: DL3008

      - name: Lint kernel-crawler
        uses: cclauss/GitHub-Action-for-pylint@45e14ae074fb20b6b176a5d803ec05eb4e25b3f0 # 06.0
        with:
          args: "pip install -r requirements.txt ; pylint kernel_crawler"
        continue-on-error: true  # allow failure for now

      - name: Lint YAML
        uses: karancode/yamllint-github-action@4052d365f09b8d34eb552c363d1141fd60e2aeb2 # v3.0.0
        with:
          yamllint_file_or_dir: '.github/workflows/'
          yamllint_strict: false
          yamllint_comment: false
          yamllint_config_filepath: .yamllint
